export const postTypes = {
    MENAGE_REQUEST: 'POST_MENAGE_REQUEST',
    MENAGE_SUCCESS: 'POST_MENAGE_SUCCESS',
    MENAGE_FAILURE: 'POST_MENAGE_FAILURE',
    GETALL_REQUEST: 'POST_GETALL_REQUEST',
    GETALL_SUCCESS: 'POST_GETALL_SUCCESS',
    GETALL_FAILURE: 'POST_GETALL_FAILURE',
    DELETE_REQUEST: 'POST_DELETE_REQUEST',
    DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
    DELETE_FAILURE: 'POST_DELETE_FAILURE',
    SET_REQUEST: 'REACT_SET_REQUEST',
    SET_SUCCESS: 'REACT_SET_SUCCESS',
    SET_FAILURE: 'REACT_SET_FAILURE',
};
